<a href="https://colab.research.google.com/github/kelvo1999/NumPy/blob/main/Introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Initialize a Python list
python_list = [2, 4, 6, 8, 10]

# Display the List
python_list

[2, 4, 6, 8, 10]

In [2]:
import numpy as np

In [3]:
# Converting the python_list to a numpy array
numpy_array1 = np.array (python_list)

# Displays the numpy array
numpy_array1

array([ 2,  4,  6,  8, 10])

In [4]:
# comparing python list and numpy array

# Create two python List say 'List_x' and 'List_y'
X_list = list(range(100000))
Y_list = list(range(100000))

In [5]:
# Import numpy Library
import numpy as np
# Create two numpy array (say 'X' end 'Y') using above two list
X = np.array(X_list)
Y = np.array(Y_list)

In [6]:
# Define a function to calculate sum
# using python Lists X_list, Y_list)
def pure_python_version():
    Z = []
    for i in range(len(X_list)):
        Z.append(X_list[i] + Y_list[i])

In [8]:
# Define a function that will perform element-wise addition of two NumPy arrays.
# Define a function to calculate sum
# using numpy arrays (X, Y)
def numpy_version():
# In numpy we can directly perform
# sum element-wise as
    Z = X + Y 

In [9]:
# Notice the time taken by both the functions (i.e. list_sum() and numpy_arr_sum()) to perform the same task.
# Import Timer class from timeit Library
from timeit import Timer

In [10]:
# You can observe here that the time taken by the python list to do the element-wise sum is much more than the NumPy arrays.

timer_obj1 = Timer("pure_python_version()", 
                   "from __main__ import pure_python_version")
timer_obj2 = Timer("numpy_version()", 
                   "from __main__ import numpy_version")

print("Pure python version:",timer_obj1.timeit(1000))
print("Numpy version:",timer_obj2.timeit(1000))

Pure python version: 11.249549860000002
Numpy version: 0.04042681700002504


In [2]:
# NumPy array of the first five even numbers
# Simplest way is using the list

even_numbers = [2,4,6,8,10]

# import numpy 

import numpy as np

# in order to display the array successfully , use np.array

numpy_even = np.array (even_numbers)

numpy_even



array([ 2,  4,  6,  8, 10])

In [4]:
# creating a numpy array with python nested list

import numpy as np

arr = np.array ([[5,6,7],[8,9,10],[11,12,13],[14,15,16]])

arr

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [5]:
# checking Numpy array size

arr.size

12

In [6]:
# checking array datatype

arr.dtype


dtype('int64')

In [7]:
# checking the shape of a numpy array

arr.shape

(4, 3)

In [8]:
# checking the dimensions of a numpy array

arr.ndim


2

In [10]:
# checking the type of object

type(arr)

numpy.ndarray

In [13]:
# checking for list

vehicles=['bus','nissan','mazda']

vehicles



['bus', 'nissan', 'mazda']

In [14]:
type(vehicles)

list

In [17]:
# creating basic numpy arrays

# 1. Array ()

arr = np.array ([[1,2,5,7],[5,2,7,6],[6,2,0,8]])

arr

array([[1, 2, 5, 7],
       [5, 2, 7, 6],
       [6, 2, 0, 8]])

In [19]:
# 2. arange ()
# this creates a collection of continuous integers

arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# zeros()
# if you want to create a collection of zero values, you can use the zeros() function available in NumPy.
# The zeros() function creates an n-dimensional array of zeros. If no shape is specified, then it will create a one-dimensional array:
# For instance, 5 means it will generate 5 zeros.

arr = np.zeros(5)

arr

array([0., 0., 0., 0., 0.])

In [23]:
# ones()
# generates an array of ones

arr = np.ones(4)

arr

array([1., 1., 1., 1.])

In [25]:
# linspace()
# linspace() generates values which are equally spaced from each other.

arr = np.linspace(start = 5, stop = 10, num=5)

arr

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])